### ISSUE TITLE
建议样式表中针对mermaid添加一下限制

### ISSUE THREAD

**Issue by htmambo** [mylxsw/wizard#154]
```css
.mermaid {
    max-width: 100%;
    overflow: auto;
}
```
这样，超宽的mermaid图就只在div里滚动了，不用整个页面都左右移动。
