### ISSUE TITLE
暗黑模式右侧文档区域没有设置，自己魔改了下，

### ISSUE THREAD

**Issue by htmambo** [mylxsw/wizard#53]
比较差异
```
diff --git a/public/assets/css/style-dark.css b/public/assets/css/style-dark.css
index 732293e..8eada72 100644
--- a/public/assets/css/style-dark.css
+++ b/public/assets/css/style-dark.css
@@ -7,16 +7,16 @@ body.wz-dark-theme {
 .wz-dark-theme a.dropdown-item {
   color: #212529;
 }
-.wz-dark-theme a.dropdown-item:hover {
+.wz-dark-theme .wz-panel-right, .wz-dark-theme .editormd-html-preview, .wz-dark-theme .wz-project-main, .wz-dark-theme a.dropdown-item:hover {
   color: #ffffff;
   background: #343a40;
 }
-.wz-dark-theme .footer {
-  background: #333;
-  color: #ffffff;
+.wz-dark-theme pre.prettyprint, .wz-dark-theme .tm-input, .wz-dark-theme .footer {
+  background: #333 !important;
+  color: #ffffff !important;
   border-top: none;
 }
-.wz-dark-theme .footer a {
+.wz-dark-theme .com, .wz-dark-theme .footer a {
   color: #aeb0b2;
 }
 .wz-dark-theme .footer a:hover {
@@ -46,12 +46,14 @@ body.wz-dark-theme {
 .wz-dark-theme .wz-box-new {
   border: none;
 }
+.wz-dark-theme .typ,
 .wz-dark-theme .wz-box-tag-star {
   color: #f1c40f !important;
 }
 .wz-dark-theme a#scrollUp {
   color: #aeb0b2;
 }
+.wz-dark-theme .kwd,
 .wz-dark-theme a#scrollUp:hover {
   color: #00aaaa;
 }
@@ -66,6 +68,7 @@ body.wz-dark-theme {
 .wz-dark-theme .wz-top-navbar a.text-dark:hover {
   color: #ffffff !important;
 }
+.wz-dark-theme .pln,
 .wz-dark-theme .wz-top-navbar .wz-top-nav-search input::-webkit-input-placeholder {
   color: #dcdcdc;
 }
@@ -193,4 +196,4 @@ body.wz-dark-theme {
 .wz-dark-theme .nav-tabs .nav-item a {
   color: #fffffc;
 }
```

**Comment by mylxsw** [comment]
能否提供下修改后的css呢，这样看实在是太困难了

**Comment by htmambo** [comment]
附上了，没有用less，直接改的css文件
```css
body.wz-dark-theme {
  background: #343a40;
}
.wz-dark-theme .wz-main-container {
  background: #343a40;
}
.wz-dark-theme a.dropdown-item {
  color: #212529;
}
.wz-dark-theme .wz-panel-right, .wz-dark-theme .editormd-html-preview, .wz-dark-theme .wz-project-main, .wz-dark-theme a.dropdown-item:hover {
  color: #ffffff;
  background: #343a40;
}
.wz-dark-theme pre.prettyprint, .wz-dark-theme .tm-input, .wz-dark-theme .footer {
  background: #333 !important;
  color: #ffffff !important;
  border-top: none;
}
.wz-dark-theme .com, .wz-dark-theme .footer a {
  color: #aeb0b2;
}
.wz-dark-theme .footer a:hover {
  color: #ffffff;
}
.wz-dark-theme .wz-left-main .material-icons,
.wz-dark-theme .wz-left-main .wz-left-nav a,
.wz-dark-theme .wz-left-main .wz-project-title > a {
  color: #aeb0b2;
}
.wz-dark-theme .wz-left-main .wz-left-nav a:hover,
.wz-dark-theme .wz-left-main .wz-left-nav li.active > a,
.wz-dark-theme .wz-left-main .wz-left-nav li.active > a:hover {
  color: #ffffff;
}
.wz-dark-theme .wz-left-main .wz-project-title > a:hover,
.wz-dark-theme .wz-left-main button:hover .material-icons {
  color: #ffffff;
}
.wz-dark-theme .wz-left-main .nav .nav-link {
  color: #bdbdbd;
}
.wz-dark-theme .wz-left-main .nav .nav-link:hover,
.wz-dark-theme .wz-left-main .nav .nav-link.active {
  color: #ffffff;
}
.wz-dark-theme .wz-box-new {
  border: none;
}
.wz-dark-theme .typ,
.wz-dark-theme .wz-box-tag-star {
  color: #f1c40f !important;
}
.wz-dark-theme a#scrollUp {
  color: #aeb0b2;
}
.wz-dark-theme .kwd,
.wz-dark-theme a#scrollUp:hover {
  color: #00aaaa;
}
.wz-dark-theme .wz-top-navbar {
  background: #303F9F !important;
  border-bottom: none !important;
}
.wz-dark-theme .wz-top-navbar a.text-dark,
.wz-dark-theme .wz-top-navbar h5 a {
  color: #e8e8e8 !important;
}
.wz-dark-theme .wz-top-navbar a.text-dark:hover {
  color: #ffffff !important;
}
.wz-dark-theme .pln,
.wz-dark-theme .wz-top-navbar .wz-top-nav-search input::-webkit-input-placeholder {
  color: #dcdcdc;
}
.wz-dark-theme .wz-panel-separator:hover {
  box-shadow: 8px 3px 5px 0 #b1b1b1;
  background: #343a40;
}
.wz-dark-theme .wz-panel-breadcrumb {
  background: #343a40;
}
.wz-dark-theme .wz-panel-breadcrumb .breadcrumb a,
.wz-dark-theme .wz-panel-breadcrumb .nav > li > button > .fa,
.wz-dark-theme .wz-panel-breadcrumb .nav > li > button > .material-icons {
  color: #bdbdbd;
}
.wz-dark-theme .swagger-editor-toolbar a {
  color: #bdbdbd;
}
.wz-dark-theme .breadcrumb-item.active,
.wz-dark-theme .wz-panel-breadcrumb a:hover,
.wz-dark-theme .wz-panel-breadcrumb .nav button:hover .fa,
.wz-dark-theme .wz-theme-indicator .material-icons,
.wz-dark-theme .swagger-editor-toolbar a:hover {
  color: #ffffff;
}
.wz-dark-theme .wz-setting-breadcrumb .breadcrumb-item {
  color: #555555;
}
.wz-dark-theme .wz-setting-breadcrumb .breadcrumb-item.active {
  color: #b1b1b1;
}
.wz-dark-theme .card:not(.card-white) {
  background: #d8d8d8;
}
.wz-dark-theme .card:not(.card-white) .card-header a {
  color: #aeb0b2;
}
.wz-dark-theme .card:not(.card-white) .card-header a:hover {
  color: #000000;
}
.wz-dark-theme .card:not(.card-white) .card-header .badge {
  color: #e4e4e4;
}
.wz-dark-theme .card:not(.card-white) .card-header .badge:hover {
  color: #ffffff;
}
.wz-dark-theme .card:not(.card-white) .wz-box-catalog {
  background-color: #4a4a4a;
  border: none;
}
.wz-dark-theme .card:not(.card-white) .wz-box-catalog:hover {
  background-color: #000000;
}
.wz-dark-theme .card:not(.card-white) .wz-box-catalog .wz-title {
  color: #fff;
}
.wz-dark-theme .card:not(.card-white) .wz-box-project {
  background-color: #4a4a4a;
}
.wz-dark-theme .card:not(.card-white) .wz-box-project:hover {
  background-color: #000000;
}
.wz-dark-theme .card:not(.card-white) .wz-box-project .wz-title,
.wz-dark-theme .card:not(.card-white) .wz-box-project .wz-page-count {
  color: #ffffff;
}
.wz-dark-theme .card:not(.card-white) .wz-main-container-full .alert-info {
  color: #4a4a4a;
  background-color: #cecece;
}
.wz-dark-theme .card:not(.card-white) .wz-main-container-full .alert-info a {
  color: #2d3a9a;
}
.wz-dark-theme .card:not(.card-white) .wz-main-container-full .alert-info a:hover {
  color: #3F51D7;
}
.wz-dark-theme .card:not(.card-white) .tm-tag {
  background: #343a40;
}
.wz-dark-theme .card:not(.card-white) .tm-tag a {
  color: #bdbdbd;
}
.wz-dark-theme .card:not(.card-white) .tm-tag a:hover {
  color: #ffffff;
}
.wz-dark-theme .card:not(.card-white) .media .media-body .wz-text-dashed {
  color: #484848;
}
.wz-dark-theme .card:not(.card-white) .media .media-body a {
  color: #585858;
}
.wz-dark-theme .card:not(.card-white) .media .media-body a:hover {
  color: #000000;
}
.wz-dark-theme .card:not(.card-white) .media .border-bottom {
  border-bottom: 1px solid #848484 !important;
}
.wz-dark-theme .card:not(.card-white) .card-footer {
  background-color: #333333;
}
.wz-dark-theme .card:not(.card-white) .card-footer a {
  color: #bdbdbd;
}
.wz-dark-theme .wz-box-catalog {
  box-shadow: 8px 7px 2px #878787b3;
}
.wz-dark-theme .wz-comment-panel {
  background: transparent;
}
.wz-dark-theme .card.card-white,
.wz-dark-theme .wz-diff-control,
.wz-dark-theme .wz-diff-result,
.wz-dark-theme .swagger-container .Pane2 {
  background: #ffffff;
}
.wz-dark-theme .wz-white-panel .card {
  background: #ffffff;
}
.wz-dark-theme .wz-white-panel .card a {
  color: rgba(0, 0, 0, 0.54);
}
.wz-dark-theme .wz-white-panel .card a:hover {
  color: #000000;
}
.wz-dark-theme .nav-tabs .nav-item a {
  color: #fffffc;
}
/*# sourceMappingURL=style-dark.css.map */

```
